### ISSUE TITLE
Linux Incompatibility with AAAParticles via "Prominence II RPG: Hasturian Era"

### ISSUE THREAD

**Issue by ofirtim** [ChloePrime/AAAParticles#42]
I saw another issue that was closed 3 weeks ago, but the fix did not help in my side.
Whenever trying to load up the game, the modpack crashes and throws this following error:

`Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'aaa_particles'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError
	at mod.chloeprime.aaaparticles.client.AAAParticlesClient.installNativeLibrary(AAAParticlesClient.java:55)
	at mod.chloeprime.aaaparticles.client.AAAParticlesClient.init(AAAParticlesClient.java:25)
	at mod.chloeprime.aaaparticles.fabric.AAAParticlesFabricClient.onInitializeClient(AAAParticlesFabricClient.java:15)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: /home/ofirtim/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Prominence II RPG- Hasturian Era/minecraft/libEffekseerNativeForJava.so: libGLU.so.1: cannot open shared object file: No such file or directory
	at java.base@17.0.12/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base@17.0.12/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base@17.0.12/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base@17.0.12/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base@17.0.12/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base@17.0.12/java.lang.Runtime.load0(Runtime.java:755)
	at java.base@17.0.12/java.lang.System.load(System.java:1957)
	at mod.chloeprime.aaaparticles.client.AAAParticlesClient.installNativeLibrary(AAAParticlesClient.java:53)
	... 12 more
`

**Comment by ChloePrime** [comment]
Try update the mod version of AAAParticles.
The latest version fixes this on Linux

**Comment by felix797** [comment]
@ChloePrime no it didn't i have the same problem
