### ISSUE TITLE
Cant run Datagen with  aaa particles

### ISSUE THREAD

**Issue by 1awless** [ChloePrime/AAAParticles#6]
when i try to run datagen (to generate recipes or such)
this error comes up

```java
[21:59:27] [main/ERROR] (Minecraft) Failed to start the minecraft server
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'aaa_particles'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[minecraft-merged-d6f9e55fab-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.2-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoSuchMethodError: 'dev.architectury.networking.NetworkChannel dev.architectury.networking.NetworkChannel.create(net.minecraft.util.Identifier)'
	at mod.chloeprime.aaaparticles.common.network.ModNetwork.<clinit>(ModNetwork.java:7) ~[aaa-particles-mIOu49Wn.jar:?]
	at mod.chloeprime.aaaparticles.AAAParticles.init(AAAParticles.java:14) ~[aaa-particles-mIOu49Wn.jar:?]
	at mod.chloeprime.aaaparticles.fabric.AAAParticlesFabric.onInitialize(AAAParticlesFabric.java:9) ~[aaa-particles-mIOu49Wn.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	... 6 more```

**Comment by ChloePrime** [comment]
The error message indicates that you does not have architectury installed in your dev environment

**Comment by ChloePrime** [comment]
Try newer versions which blocks this mod from doing anything when running in datagen mode

**Comment by ChloePrime** [comment]
Please include architectury-api in your dependency
