### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by CatrooMC** [ChloePrime/AAAParticles#8]
So I'm using AAA particles for a forge 1.20.1 for a mod pack of a Lore SMP that I'm working on, I'm currently doing a compatibility test to see if it works with Mac as some people who are interested play on mac, I tried and I continuously crashed, I removed AAA and it worked fine, here's the crash error I got. is the mod not compatible with Mac's graphic system? 

[09:20:13] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: aaa_particles, class mod.chloeprime.aaaparticles.forge.AAAParticlesForge
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
	at mod.chloeprime.aaaparticles.client.installer.JarExtractor.extract(JarExtractor.java:15) ~[aaa_particles-1.20.1-1.0.7-forge.jar%23226!/:?] {re:classloading}
	at mod.chloeprime.aaaparticles.client.AAAParticlesClient.installNativeLibrary(AAAParticlesClient.java:40) ~[aaa_particles-1.20.1-1.0.7-forge.jar%23226!/:?] {re:classloading}
	at mod.chloeprime.aaaparticles.client.AAAParticlesClient.init(AAAParticlesClient.java:22) ~[aaa_particles-1.20.1-1.0.7-forge.jar%23226!/:?] {re:classloading}
	at mod.chloeprime.aaaparticles.forge.AAAParticlesForge.<init>(AAAParticlesForge.java:22) ~[aaa_particles-1.20.1-1.0.7-forge.jar%23226!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.17.jar%23302!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.17.jar%23301!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

**Comment by ChloePrime** [comment]
This mod uses a native library that was compiled by myself, and I don't have any mac devices.
So MacOS is not supported :(

**Comment by CatrooMC** [comment]
completely fair I just wanted to ask, Thank you! :D

**Comment by ChloePrime** [comment]
Made this mod no-op on MacOS instead of crashing in version 1.2.2
